spring:
  datasource:
    url: jdbc:mysql://172.19.0.2:3306/boot_webapp
    driverClassName: com.mysql.cj.jdbc.Driver
    username: app_user
    password: ENC(bA8MQzQyTI8oD4YOWPeWlhrH1mtlLiTfCIbbbkSTsJkBBrOgFjyIUFYKRqqCo551ExcnDGeJN+m1P3Bg12/yyA==)
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
        hibernate.format_sql: false

server:
  shutdown: graceful
