spring:
  datasource:
    url: jdbc:mysql://172.19.0.2:3306/boot_webapp
    driverClassName: com.mysql.cj.jdbc.Driver
    username: app_user
    password: secured_passwd123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
        hibernate.format_sql: false

server:
  shutdown: graceful
