spring:
  datasource:
    url: ${jdbc.url-path}
    driverClassName: ${jdbc.driver}
    username: ${jdbc.user-name}
    password: ${jdbc.passwd}
  jpa:
    database-platform: ${jdbc.dialect}
    generate-ddl: true
    hibernate:
        ddl-auto: update
    show-sql: ${jdbc.sql-show}
    properties:
        hibernate.format_sql: ${jdbc.sql-show}

server:
  shutdown: graceful
